# Generated by Django 5.2.15 on 2026-06-18 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToothSurfaceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('mesial', 'Mesial'), ('distal', 'Distal'), ('occlusal', 'Occlusal / Incisal'), ('buccal', 'Buccal / Facial'), ('lingual', 'Lingual / Palatal')], max_length=10)),
                ('procedure_code', models.CharField(default='clear', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surface_records', to='records.toothrecord')),
            ],
            options={
                'ordering': ['surface'],
                'unique_together': {('tooth', 'surface')},
            },
        ),
    ]
